### ISSUE TITLE
Is this software still maintained? Can it be built on CentOS7? 

### ISSUE THREAD

**Issue by james-vincent** [continuous-symmetry-measure/csm#7]
We're trying to include this title with SBGrid. Is it possible to build on CentOS7?

**Comment by ituvi** [comment]
Hello
The development of the code is currently on hold, but we can try to help. 
We used to work on CENTOS7 and were able to install the CSM code. However, it technically complex due to the integration with the Open Babel libraries. 
We strongly recommend to use the docker image of the code - this is very simple to install. A link appears in the main readme file.
Good luck.
